name: Cleanup Duplicate Builds

# When a new workflow build is requested, run cleanup action
# This will hopefully reduce the number of times we need to run this workflow 
on:
  workflow_run:
    workflows: ["OpenLiberty CI"]
    types: ['requested']

jobs:
  cleanup-prs:
    #if: github.repository == 'OpenLiberty/open-liberty'
    name: "Cleanup Duplicate Builds"
    runs-on: ubuntu-18.04
    steps:
    - uses: potiuk/cancel-workflow-runs@master
      name: "Cancel duplicate workflow runs"
      with:
        cancelMode: duplicates
        cancelFutureDuplicates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        sourceRunId: ${{ github.event.workflow_run.id }}
        notifyPRCancel: true